version: '3'

volumes:
  db:
  # nextcloud:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:

services:
  ##### Proxy

  proxy:
    container_name: 'reverse-proxy'
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      # - 6600:6600
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    container_name: 'letsencrypt-companion'
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  ##### Nextcloud

  nextcloud-app:
    container_name: 'nextcloud-app'
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /home/nextcloud:/var/www/nextcloud
    environment:
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
      - OVERWRITEWEBROOT=/nextcloud
      - NEXTCLOUD_DATA_DIR=/var/www/nextcloud/data
    env_file:
      - db.env
    depends_on:
      - nextcloud-db
      - nextcloud-redis

  nextcloud-server:
    container_name: 'nextcloud-server'
    build: ./nextcloud/server
    restart: always
    volumes:
      - /home/nextcloud:/var/www/nextcloud:ro
    environment:
      - VIRTUAL_HOST=art-s.tplinkdns.com
      - VIRTUAL_PATH=/nextcloud
      - LETSENCRYPT_HOST=art-s.tplinkdns.com
      - LETSENCRYPT_EMAIL=ArtemSmaznov@gmail.com
    depends_on:
      - nextcloud-app
    networks:
      - proxy-tier
      - default

  nextcloud-cron:
    container_name: 'nextcloud-cron'
    build: ./nextcloud/cron
    restart: always
    volumes:
      - /home/nextcloud:/var/www/nextcloud
    environment:
      - OVERWRITEWEBROOT=/nextcloud
      - NEXTCLOUD_DATA_DIR=/var/www/nextcloud/data
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis

  nextcloud-db:
    container_name: 'nextcloud-db'
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=uhcai7pu5f20HosvvXIa6rBtk
    env_file:
      - db.env

  nextcloud-redis:
    container_name: 'nextcloud-redis'
    image: redis:alpine
    restart: always

  ##### Music

  # # This neesd to be updated from the tmp one
  # music-mpd:
  #   image: vimagick/mpd
  #   restart: unless-stopped
  #   volumes:
  #     - ./music/mpd/mpd.conf:/etc/mpd.conf:ro
  #     - /home/music:/var/lib/mpd/music
  #   environment:
  #     - VIRTUAL_HOST=art-s.tplinkdns.com
  #     # - VIRTUAL_PATH=/music
  #     # - VIRTUAL_PORT=6600
  #     # - VIRTUAL_PORT=6600,8800
  #   networks:
  #     - proxy-tier

  # # This should be the same as the tmp one
  # music-webdav:
  #   build: ./music/webdav
  #   restart: always
  #   volumes:
  #     - ./music/webdav/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /home/music:/srv/http/music
  #   environment:
  #     - VIRTUAL_HOST=art-s.tplinkdns.com
  #     - VIRTUAL_PATH=/music
  #   networks:
  #     - proxy-tier

  ##### Debug

  test-hello:
    container_name: 'test-hello'
    image: nginx
    restart: always
    volumes:
      - ./test/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./test/www:/var/www/hello
    environment:
      - VIRTUAL_HOST=art-s.tplinkdns.com
      - VIRTUAL_PATH=/hello
    networks:
      - proxy-tier
