secrets:
  pihole_password:
    file: secrets/pihole_password

services:
  pi-hole:
    image: pihole/pihole:${PIHOLE_VERSION}
    container_name: pi-hole
    hostname: pi-hole
    tty: true # enable colorized logs
    restart: always
    cap_add:
      # required if you are using pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # required if you are using pi-hole as your ntp client to be able to set the host's system time
      - SYS_TIME
      # optional, if pi-hole should get some more processing time
      - SYS_NICE
    ports:
      # dns ports
      - 53:53/tcp
      - 53:53/udp
      # default http port
      - 80:80/tcp
      # default https port. FTL will generate a self-signed certificate
      - 443:443/tcp
      # uncomment the below if using pi-hole as your dhcp server
      - 67:67/udp
      # uncomment the line below if you are using pi-hole as your ntp server
      - 123:123/udp
    volumes:
      - {VOLUMES_DIR}/pi-hole/etc:/etc/pihole
      - {VOLUMES_DIR}/pi-hole/dnsmasq.d:/etc/dnsmasq.d
    environment:
      FTLCONF_LOCAL_IPV4: ${MY_SERVER_IP}
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      FTLCONF_webserver_api_password: /run/secrets/pihole_password
        # if using docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'

      PIHOLE_UID: ${UID}
      PIHOLE_GID: ${DGID}
      PROXY_LOCATION: pi-hole
      TZ: ${TIME_ZONE}
    extra_hosts:
      # Resolve to nothing domains (terminate connection)
      - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
    secrets:
      - pihole_password
