version: '3'
secrets:
  pihole_password:
    file: secrets/pihole_password

services:
  pi-hole:
    image: pihole/pihole:${PIHOLE_VERSION}
    container_name: pi-hole
    hostname: pi-hole
    tty: true # enable colorized logs
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/pi-hole/etc:/etc/pihole
      - /home/pi-hole/dnsmasq.d:/etc/dnsmasq.d
    environment:
      - VIRTUAL_HOST=${PIHOLE_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${PIHOLE_HOST}
      - LETSENCRYPT_EMAIL=${MY_EMAIL}
      - FTLCONF_LOCAL_IPV4=${MY_SERVER_IP}
      - WEBPASSWORD_FILE=/run/secrets/pihole_password
      - PROXY_LOCATION=pi-hole
      - TZ=${TIME_ZONE}
    extra_hosts:
      # Resolve to nothing domains (terminate connection)
      - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
    secrets:
      - pihole_password
